# fly.toml app configuration file generated for backendface on 2025-05-16T15:00:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendface'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  
[[http_service.checks]]
  interval = "30s"
  timeout = "10s"
  grace_period = "2m"  # Extended for TensorFlow init
  path = "/health"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1