"""added foreign key

Revision ID: 0a65ef00ea4d
Revises: 854b27c06459
Create Date: 2025-05-09 19:59:44.762627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a65ef00ea4d'
down_revision = '854b27c06459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.String(length=11), nullable=True))
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
