"""Add connection_strength to Attendancelog

Revision ID: 0f679b3df23b
Revises: 3ac1d643494c
Create Date: 2025-04-18 19:06:25.206566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f679b3df23b'
down_revision = '3ac1d643494c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_strength', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.drop_column('connection_strength')

    # ### end Alembic commands ###
