"""Make face_encoding nullable

Revision ID: 2651d7c716ad
Revises: 338f607bd163
Create Date: 2025-04-11 16:08:16.313727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2651d7c716ad'
down_revision = '338f607bd163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
