"""Updated face_encoding column type to JSON

Revision ID: 338f607bd163
Revises: 479203248c09
Create Date: 2025-01-02 00:57:44.108976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338f607bd163'
down_revision = '479203248c09'
branch_labels = None
depends_on = None


def upgrade():
    # Other migration steps...
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('face_encoding', type_=sa.JSON, postgresql_using='face_encoding::json')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('student', schema=None) as batch_op:
        # Revert the face_encoding column type back to TEXT if necessary
        batch_op.alter_column('face_encoding', type_=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###

