"""Add teacher_id to Attendancelog

Revision ID: 89dc62dbcd1f
Revises: c250097b4cd3
Create Date: 2025-06-12 13:11:45.516567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dc62dbcd1f'
down_revision = 'c250097b4cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.String(length=11), nullable=False))
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
