"""Add course_code and description to course, fix session_id foreign key, update attendancelog

Revision ID: c250097b4cd3
Revises: ed9174543025
Create Date: 2025-06-12 06:24:49.380036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250097b4cd3'
down_revision = 'ed9174543025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.alter_column('connection_strength',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('attendancelog_teacher_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'attendance_session', ['session_id'], ['id'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendancelog_teacher_id_fkey', 'teacher', ['teacher_id'], ['teacher_id'])
        batch_op.alter_column('connection_strength',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
