"""Updated Attendancelog with session_id as primary key

Revision ID: ce4fe8e1ff18
Revises: 5633b3bebf04
Create Date: 2025-04-18 17:24:22.222949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4fe8e1ff18'
down_revision = '5633b3bebf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.drop_column('attendance_id')
        batch_op.drop_column('session')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
