"""edits

Revision ID: da9b3e06c14f
Revises: 89dc62dbcd1f
Create Date: 2025-06-12 13:52:27.923956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da9b3e06c14f'
down_revision = '89dc62dbcd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('session_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attendance_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('marking_ip', sa.String(length=45), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('marking_ip')
        batch_op.drop_column('attendance_source')
        batch_op.drop_column('verification_method')
        batch_op.drop_column('verification_score')

    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('session_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
