"""Update session number

Revision ID: dd941eade02b
Revises: ce4fe8e1ff18
Create Date: 2025-04-18 17:33:43.221696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd941eade02b'
down_revision = 'ce4fe8e1ff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_column('session_number')

    # ### end Alembic commands ###
