"""empty message

Revision ID: ed1d0d4c933c
Revises: a524cd0be58e
Create Date: 2025-04-14 16:25:07.436650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed1d0d4c933c'
down_revision = 'a524cd0be58e'
branch_labels = None
depends_on = None


def upgrade():
    # Add a new column of type FLOAT[]
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_face_encoding', postgresql.ARRAY(sa.Float())))

    # Copy and convert the data from the old `face_encoding` to the new column
    op.execute("""
        UPDATE student 
        SET new_face_encoding = ARRAY(
            SELECT json_array_elements_text(face_encoding)::FLOAT
            FROM student
            LIMIT 1
        )
    """)

    # Drop the old column
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('face_encoding')

    # Rename the new column to the original column name
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('new_face_encoding', new_column_name='face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.ARRAY(sa.Float()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
