"""endtime

Revision ID: ed9174543025
Revises: 0a65ef00ea4d
Create Date: 2025-05-09 20:52:06.704770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9174543025'
down_revision = '0a65ef00ea4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
