"""Update student model to support bcrypt

Revision ID: ede5ee9ec3a2
Revises: 2651d7c716ad
Create Date: 2025-04-11 16:40:31.296143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede5ee9ec3a2'
down_revision = '2651d7c716ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###
