"""Add

Revision ID: f5e46da187ee
Revises: fe045d2bd239
Create Date: 2025-06-12 14:33:48.206784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e46da187ee'
down_revision = 'fe045d2bd239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_column('total_attempts')
        batch_op.drop_column('successful_verifications')
        batch_op.drop_column('liveness_check_required')
        batch_op.drop_column('verification_required')
        batch_op.drop_column('failed_verifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_verifications', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('liveness_check_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('successful_verifications', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
