"""Add enhanced verification tracking

Revision ID: fe045d2bd239
Revises: da9b3e06c14f
Create Date: 2025-06-12 14:22:08.997827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe045d2bd239'
down_revision = 'da9b3e06c14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('liveness_check_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('total_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('successful_verifications', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_verifications', sa.Integer(), nullable=True))

    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liveness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempts_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('attendance_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendancelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('verification_details')
        batch_op.drop_column('last_attempt')
        batch_op.drop_column('attempts_count')
        batch_op.drop_column('verification_timestamp')
        batch_op.drop_column('liveness_score')

    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_column('failed_verifications')
        batch_op.drop_column('successful_verifications')
        batch_op.drop_column('total_attempts')
        batch_op.drop_column('liveness_check_required')
        batch_op.drop_column('verification_required')

    # ### end Alembic commands ###
